# Generated by Django 2.0.2 on 2019-11-24 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=1000, verbose_name='描述')),
                ('skill', models.CharField(blank=True, max_length=500, verbose_name='所需技能')),
                ('industry', models.CharField(blank=True, max_length=200, verbose_name='所属行业')),
                ('over_time', models.CharField(blank=True, max_length=200, verbose_name='完成时间')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('progress', models.CharField(blank=True, max_length=200, verbose_name='完成进度')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='工作地址')),
                ('money', models.CharField(blank=True, default='0', max_length=100, verbose_name='项目预算')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_pass', models.BooleanField(default=False, verbose_name='是否审核通过')),
            ],
        ),
    ]
