# Generated by Django 2.0.2 on 2019-11-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='project',
            name='over_time',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='完成进度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='所需技能'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='标题'),
        ),
    ]
